### ISSUE TITLE
Error: Scope wasn't granted in OAuth2.

### ISSUE THREAD

**Issue by bensuperpc** [TreeBen77/discord-oauth2.py#4]
I get an error when I try to join my bot to a server, it has successfully joined the server, I don't know why there is this error :/

The error output:

```bash
[2022-06-05 13:07:29,708] ERROR in app: Exception on /oauth2 [GET]
Traceback (most recent call last):
  File "/home/bensuperpc/.local/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bensuperpc/.local/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bensuperpc/.local/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bensuperpc/.local/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/run/media/bensuperpc/MainT7/Depot_git/repos_perso/discord-bot/app.py", line 34, in oauth
    tokenObject.access.guilds_join(XXXXXXXXXXXXXXX)
  File "/run/media/bensuperpc/MainT7/Depot_git/repos_perso/discord-bot/discordoauth2.py", line 54, in guilds_join
    if user_object.status_code == 401: raise Exception(f"Scope wasn't granted in OAuth2.")
Exception: Scope wasn't granted in OAuth2.
```

The code:

```python
client = discordOauth2(client=XXXXXXXXXXX, secret="XXXXXXXXXXXXXXX",
redirect="http://localhost:8080/oauth2", token="XXXXXXXX")

  # Your OAuth2 url, you can make one a https://discord.dev
  return redirect("https://discord.com/api/oauth2/authorize?client_id=XXXXXXXXXXX&permissions=8&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Foauth2&response_type=code&scope=bot%20guilds%20guilds.join%20guilds.members.read%20connections%20email%20identify")

  tokenObject.access.guilds_join(XXXXXXXXXX)
```

Selected fields:

![Screenshot_20220605_131815](https://user-images.githubusercontent.com/28039927/172048007-b37ac040-5fcd-471f-b921-3cbd51348917.png)

![Screenshot_20220605_132347](https://user-images.githubusercontent.com/28039927/172048173-d3d41521-d369-49cc-a395-b4cd63bffef2.png)

![Screenshot_20220605_132407](https://user-images.githubusercontent.com/28039927/172048180-63d954c7-aa18-4df6-9a81-35ef4445ba16.png)

**Comment by treeben77** [comment]
are you sure the bot has the create invite permission in the server you're trying to join? I should probably make it clearer tbh.
